/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ma.project.forms;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.awt.Color;
import java.awt.Image;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import ma.bean.project.Adherant;
import ma.project.service.*;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import ma.bean.project.MyStyles;

/**
 *
 * @author Hakim
 */
public class AdherantForm extends javax.swing.JFrame {

    /**
     * Creates new form AdherantForm
     */
    DefaultTableModel tablemodel;
    ArrayList<Adherant> adhr;
    Adherant adr;
    LocalDateTime now;
    int cpt = 1;
    GestionAdherant gst_adhr = new GestionAdherant();

    public AdherantForm() {
        initComponents();
        tablemodel = (DefaultTableModel) jTable1.getModel();
        ShowData();

        MyStyles.GetMyStyle(btn_ajt, btn_mod, btn_sup, lbl_bg, this);
        
        jTable1.getTableHeader().setForeground(Color.BLACK);
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.ORANGE);
        for (int i = 0; i < jTable1.getModel().getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        

    }

    public void ShowData() {
        adhr = gst_adhr.ShowData();
        int rowCount = tablemodel.getRowCount();

        for (int i = 0; i < rowCount; i++) {
            tablemodel.removeRow(i);
        }

        for (Adherant ad : adhr) {
//            System.err.println(ad.getIdAdr()+" "+ ad.getNumAdherant()+" "+ ad.getNom()+" "+
//                ad.getCin()+" "+ ad.getTele()+" "+ ad.getAdresse()+" "+ad.getEmail());

            tablemodel.addRow(new Object[]{ad.getIdAdr(), ad.getNumAdherant(), ad.getNom(),
                ad.getCin(), ad.getTele(), ad.getAdresse(), ad.getEmail()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        nom = new javax.swing.JTextField();
        cin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tele = new javax.swing.JTextField();
        btn_ajt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        adresse = new javax.swing.JTextField();
        btn_mod = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_sup = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        lbl_bar = new javax.swing.JLabel();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 0));
        setForeground(java.awt.Color.white);
        setSize(new java.awt.Dimension(700, 550));
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Asimov", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Gestion des Adherants");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 60, 280, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Num Adherant", "Nom", "CIN", "Telephone", "Adresse", "Email"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(0, 204, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(22, 140, 660, 188);
        getContentPane().add(nom);
        nom.setBounds(70, 340, 130, 30);
        getContentPane().add(cin);
        cin.setBounds(310, 340, 110, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CIN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 350, 30, 14);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nom");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 350, 30, 14);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Telephone");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 350, 60, 14);
        getContentPane().add(tele);
        tele.setBounds(140, 390, 190, 30);

        btn_ajt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ajt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ajtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ajtMouseExited(evt);
            }
        });
        btn_ajt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajtActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ajt);
        btn_ajt.setBounds(240, 460, 50, 50);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Adresse");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 400, 50, 14);
        getContentPane().add(adresse);
        adresse.setBounds(530, 340, 120, 30);

        btn_mod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_modMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_modMouseExited(evt);
            }
        });
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mod);
        btn_mod.setBounds(330, 460, 50, 50);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 400, 40, 14);

        btn_sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_supMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_supMouseExited(evt);
            }
        });
        btn_sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sup);
        btn_sup.setBounds(430, 460, 50, 50);
        getContentPane().add(email);
        email.setBounds(430, 390, 190, 30);
        getContentPane().add(lbl_bar);
        lbl_bar.setBounds(4, 4, 690, 30);

        lbl_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/bg.jpg"))); // NOI18N
        getContentPane().add(lbl_bg);
        lbl_bg.setBounds(0, 0, 690, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        adhr = gst_adhr.ShowData();
        for (Adherant ad : adhr) {
            if (tablemodel.getValueAt(jTable1.getSelectedRow(), 0).equals(ad.getIdAdr())) {
                nom.setText(ad.getNom());
                cin.setText(ad.getCin());
                adresse.setText(ad.getAdresse());
                tele.setText(ad.getTele());
                email.setText(ad.getEmail());
                break;

            }
        }
        btn_mod.setEnabled(true);
        btn_sup.setEnabled(true);
        //        System.err.println((int)tablemodel.getValueAt(jTable1.getSelectedRow(), 0)+" "+(String)tablemodel.getValueAt(jTable1.getSelectedRow(), 1));
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supActionPerformed
        adr = new Adherant((int) tablemodel.getValueAt(jTable1.getSelectedRow(), 0),
                (String) tablemodel.getValueAt(jTable1.getSelectedRow(), 1));
        gst_adhr.DeleteData(adr);
        ShowData();
    }//GEN-LAST:event_btn_supActionPerformed

    private void btn_supMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supMouseExited
        btn_sup.setIcon(new ImageIcon(new ImageIcon("src\\files\\delete.png").getImage()
                .getScaledInstance(btn_sup.getWidth(), btn_sup.getHeight(), Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_btn_supMouseExited

    private void btn_supMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supMouseEntered
        btn_sup.setIcon(new ImageIcon(new ImageIcon("src\\files\\delete_clicked.png").getImage()
                .getScaledInstance(btn_sup.getWidth(), btn_sup.getHeight(), Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_btn_supMouseEntered

    private void btn_ajtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajtActionPerformed
        now = LocalDateTime.now();
        String num = now.getDayOfMonth() + "" + now.getMonthValue() + "" + now.getYear() + "00" + cpt;
        adr = new Adherant(num, nom.getText(), cin.getText(), tele.getText(), adresse.getText(), email.getText());
        gst_adhr.InsertData(adr);
        ShowData();
    }//GEN-LAST:event_btn_ajtActionPerformed

    private void btn_ajtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ajtMouseExited
        btn_ajt.setIcon(new ImageIcon(new ImageIcon("src\\files\\add.png").getImage()
                .getScaledInstance(btn_ajt.getWidth(), btn_ajt.getHeight(), Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_btn_ajtMouseExited

    private void btn_ajtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ajtMouseEntered
        btn_ajt.setIcon(new ImageIcon(new ImageIcon("src\\files\\add_clicked.png").getImage()
                .getScaledInstance(btn_ajt.getWidth(), btn_ajt.getHeight(), Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_btn_ajtMouseEntered

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed

        adr = new Adherant((int) tablemodel.getValueAt(jTable1.getSelectedRow(), 0),
                (String) tablemodel.getValueAt(jTable1.getSelectedRow(), 1), nom.getText(),
                cin.getText(), tele.getText(), adresse.getText(), email.getText());

        gst_adhr.UpdateData(adr);
        ShowData();
    }//GEN-LAST:event_btn_modActionPerformed

    private void btn_modMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modMouseExited
        btn_mod.setIcon(new ImageIcon(new ImageIcon("src\\files\\edit.png").getImage()
                .getScaledInstance(btn_mod.getWidth(), btn_mod.getHeight(), Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_btn_modMouseExited

    private void btn_modMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modMouseEntered
        btn_mod.setIcon(new ImageIcon(new ImageIcon("src\\files\\edit_clicked.png").getImage()
                .getScaledInstance(btn_mod.getWidth(), btn_mod.getHeight(), Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_btn_modMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdherantForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdherantForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdherantForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdherantForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdherantForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresse;
    private javax.swing.JButton btn_ajt;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_sup;
    private javax.swing.JTextField cin;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_bar;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField tele;
    // End of variables declaration//GEN-END:variables
}
