/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ma.project.forms;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import ma.bean.project.*;
import ma.project.service.GestionAdherant;
import ma.project.service.GestionEmprinte;
import ma.project.service.GestionLivre;

/**
 *
 * @author Hakim
 */
public class EmprinteForm extends javax.swing.JFrame {

    /**
     * Creates new form EmprinteForm
     */
    DefaultTableModel tablemodel;
    DefaultComboBoxModel modelcmb_adr, modelcmb_lvr;

    GestionLivre gst_lvr = new GestionLivre();
    GestionAdherant gst_adr = new GestionAdherant();
    GestionEmprinte gst_emp = new GestionEmprinte();

    ArrayList<Livre> arr_livre;
    ArrayList<Adherant> arr_adherant;
    ArrayList<Emprinte> arr_emp;
    int idLivre = 0, idLivreSelectionne = 0, idAdherant = 0, NbrEmp = 0;
    Livre updateEmp = new Livre();

    public EmprinteForm() {
        initComponents();

        arr_livre = gst_lvr.ShowData();
        arr_adherant = gst_adr.ShowData();
        arr_emp = gst_emp.ShowData();

        tablemodel = (DefaultTableModel) jTable1.getModel();
        modelcmb_adr = (DefaultComboBoxModel) cmb_adr.getModel();
        modelcmb_lvr = (DefaultComboBoxModel) cmb_lvr.getModel();
        ShowTableData();
        ShowComboData();
        btn_mod.setEnabled(false);
        btn_sup.setEnabled(false);

        MyStyles.GetMyStyle(btn_ajt, btn_mod, btn_sup, lbl_bg, this);

    }

    public void ShowComboData() {
        arr_livre = gst_lvr.ShowData();
        arr_adherant = gst_adr.ShowData();

        modelcmb_lvr.removeAllElements();
        arr_livre.forEach((lv) -> {
            modelcmb_lvr.addElement(lv);
        });

        modelcmb_adr.removeAllElements();
        arr_adherant.forEach((ad) -> {
            modelcmb_adr.addElement(ad);
        });

    }

    public void ShowTableData() {

        arr_emp = gst_emp.ShowData();

        int rowCount = tablemodel.getRowCount();

        for (int i = 0; i < rowCount; i++) {
            tablemodel.removeRow(0);
        }
        for (Emprinte em : arr_emp) {
            tablemodel.addRow(new Object[]{em.getIdEmp(), em.getIdlivreEmp(),
                em.getIdAdherant(), em.getDateEmp(), em.getDateExp()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_lvr = new javax.swing.JComboBox<>();
        date_emp = new com.toedter.calendar.JDateChooser();
        date_exp = new com.toedter.calendar.JDateChooser();
        cmb_adr = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_ajt = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();
        btn_sup = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Livre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(34, 317, 23, 14);

        jLabel2.setText("Date Empriente");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(34, 367, 74, 14);

        getContentPane().add(cmb_lvr);
        cmb_lvr.setBounds(139, 314, 141, 20);
        getContentPane().add(date_emp);
        date_emp.setBounds(139, 361, 146, 20);
        getContentPane().add(date_exp);
        date_exp.setBounds(415, 355, 181, 20);

        getContentPane().add(cmb_adr);
        cmb_adr.setBounds(419, 317, 146, 20);

        jLabel3.setText("Date Experation");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 361, 78, 14);

        jLabel4.setText("Adherant");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 320, 45, 14);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Livre", "Adherant", "Date Empriente", "Date Experation"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(34, 87, 562, 182);

        btn_ajt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajtActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ajt);
        btn_ajt.setBounds(185, 390, 33, 9);

        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mod);
        btn_mod.setBounds(236, 390, 33, 9);

        btn_sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sup);
        btn_sup.setBounds(287, 390, 33, 9);

        jLabel5.setText("Gestion des Emprientes");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(216, 42, 112, 14);
        getContentPane().add(lbl_bg);
        lbl_bg.setBounds(0, 0, 630, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ajtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajtActionPerformed

        for (Livre lv : arr_livre) {
            if (modelcmb_lvr.getSelectedItem().equals(lv)) {
                idLivre = lv.getIdLivre();
                updateEmp = new Livre(lv.getIdLivre(), lv.getNbrEmp() + 1);
                break;
            }
        }
        for (Adherant ad : arr_adherant) {
            if (modelcmb_adr.getElementAt(cmb_adr.getSelectedIndex()).equals(ad)) {
                idAdherant = ad.getIdAdr();

                break;
            }
        }
        Emprinte em = new Emprinte(idLivre, date_emp.getDate(), date_exp.getDate(), idAdherant);

        gst_emp.InsertData(em);

        gst_lvr.UpdateNombreEmp(updateEmp);

        ShowTableData();
        System.err.println("Fin");

    }//GEN-LAST:event_btn_ajtActionPerformed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        for (Livre lv : arr_livre) {
            if (modelcmb_lvr.getSelectedItem().equals(lv)) {
                idLivre = lv.getIdLivre();
//                System.out.println(lv.getIdLivre());
                break;
            }
        }
        for (Adherant ad : arr_adherant) {
            if (modelcmb_adr.getElementAt(cmb_adr.getSelectedIndex()).equals(ad)) {
                idAdherant = ad.getIdAdr();
//                System.out.println(ad.getIdAdr());
                break;
            }
        }
        Emprinte em = new Emprinte((int) tablemodel.getValueAt(jTable1.getSelectedRow(), 0), idLivre, date_emp.getDate(), date_exp.getDate(), idAdherant);
        gst_emp.UpdateData(em);
        ShowTableData();
    }//GEN-LAST:event_btn_modActionPerformed

    private void btn_supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supActionPerformed
        Emprinte em = new Emprinte((int) tablemodel.getValueAt(jTable1.getSelectedRow(), 0));
        gst_emp.DeleteData(em);
        updateEmp = new Livre(idLivreSelectionne, NbrEmp - 1);
        gst_lvr.UpdateNombreEmp(updateEmp);
        ShowTableData();
    }//GEN-LAST:event_btn_supActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        btn_mod.setEnabled(true);
        btn_sup.setEnabled(true);

        arr_emp = gst_emp.ShowData();

        for (Emprinte em : arr_emp) {
            if (tablemodel.getValueAt(jTable1.getSelectedRow(), 0).equals(em.getIdEmp())) {
                for (Livre livre : arr_livre) {
                    if (livre.getIdLivre() == em.getIdlivreEmp()) {
                        cmb_lvr.setSelectedItem(livre);
                        idLivreSelectionne = livre.getIdLivre();
                        NbrEmp = livre.getNbrEmp();
                        break;
                    }
                }
                for (Adherant ad : arr_adherant) {
                    if (ad.getIdAdr() == em.getIdAdherant()) {
                        cmb_adr.setSelectedItem(ad);
                        break;

                    }
                }
                date_emp.setDate(em.getDateEmp());
                date_exp.setDate(em.getDateExp());

                break;
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        btn_mod.setEnabled(false);
        btn_sup.setEnabled(false);
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmprinteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmprinteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmprinteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmprinteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmprinteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajt;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_sup;
    private javax.swing.JComboBox<String> cmb_adr;
    private javax.swing.JComboBox<String> cmb_lvr;
    private com.toedter.calendar.JDateChooser date_emp;
    private com.toedter.calendar.JDateChooser date_exp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_bg;
    // End of variables declaration//GEN-END:variables
}
