/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ma.project.forms;

import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import ma.bean.project.Fonction;
import ma.bean.project.Fonctionnaire;
import ma.bean.project.MyStyles;
import ma.project.service.*;

/**
 *
 * @author Hakim
 */
public class FonctionnaireForm extends javax.swing.JFrame {

    /**
     * Creates new form FonctionnaireForm
     */
    DefaultTableModel tablemodel;
    DefaultComboBoxModel modelcmb_fct;
    ArrayList<Fonctionnaire> arr_fctn;
    ArrayList<Fonction> arr_fct;
    Fonctionnaire fctn;
    Fonction fct;
    int cpt = 1;
    GestionFonctionnaire gst_fonctionnaire = new GestionFonctionnaire();
    GestionFonction gst_fonction = new GestionFonction();

    public FonctionnaireForm() {
        initComponents();
        tablemodel = (DefaultTableModel) jTable1.getModel();
        modelcmb_fct = (DefaultComboBoxModel) jComboBox1.getModel();
        ShowData();
        
       MyStyles.GetMyStyle(btn_ajt, btn_mod, btn_sup, jLabel8, this);
    }

    public void ShowData() {
        arr_fctn = gst_fonctionnaire.ShowData();
        arr_fct = gst_fonction.ShowData();

        int rowCount = tablemodel.getRowCount();

        modelcmb_fct.removeAllElements();
        arr_fct.forEach((f) -> {
            modelcmb_fct.addElement(f);
        });

        for (int i = 0; i < rowCount; i++) {
            tablemodel.removeRow(i);
        }

        for (Fonctionnaire o : arr_fctn) {

            tablemodel.addRow(new Object[]{o.getIdFonctionnaire(), o.getNom(), o.getCin(), o.getAdresse(), o.getTele(),
                o.getEmail(), o.getFonction().toString()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btn_ajt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btn_mod = new javax.swing.JButton();
        btn_sup = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(700, 550));
        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nom");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 350, 30, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(90, 350, 112, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CIN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 360, 40, 14);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Telephone");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 410, 60, 14);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fonction");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 410, 60, 14);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(310, 350, 112, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(90, 400, 140, 30);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(520, 400, 130, 30);

        btn_ajt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajtActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ajt);
        btn_ajt.setBounds(210, 460, 50, 50);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Adresse");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 410, 60, 14);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(310, 400, 130, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(520, 350, 150, 30);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Email");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(460, 360, 30, 14);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom", "CIN", "Adresse", "Telephone", "Email", "Fonction"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 150, 667, 160);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gestion des Fonctionnaire");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(260, 70, 160, 14);

        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mod);
        btn_mod.setBounds(330, 460, 50, 50);

        btn_sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sup);
        btn_sup.setBounds(440, 460, 50, 50);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 700, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supActionPerformed
        fctn = new Fonctionnaire((int) tablemodel.getValueAt(jTable1.getSelectedRow(), 0));
        gst_fonctionnaire.DeleteData(fctn);
        ShowData();
    }//GEN-LAST:event_btn_supActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        arr_fctn = gst_fonctionnaire.ShowData();
        for (Fonctionnaire o : arr_fctn) {
            if (tablemodel.getValueAt(jTable1.getSelectedRow(), 0).equals(o.getIdFonctionnaire())) {
                jTextField1.setText(o.getNom());
                jTextField2.setText(o.getCin());
                jTextField3.setText(o.getAdresse());
                jTextField4.setText(o.getTele());
                jTextField5.setText(o.getEmail());
                for (Fonction f : arr_fct) {
                    if (o.getFonction().getFonction().equals(f.getFonction())) {
                        jComboBox1.setSelectedItem(f);
                        fct = f;
                        break;
                    }
                }
                break;

            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        fctn = new Fonctionnaire((int) tablemodel.getValueAt(jTable1.getSelectedRow(), 0), jTextField1.getText(),
                jTextField2.getText(), jTextField3.getText(), jTextField4.getText(), jTextField5.getText(), fct);
        gst_fonctionnaire.UpdateData(fctn);
        ShowData();
    }//GEN-LAST:event_btn_modActionPerformed

    private void btn_ajtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajtActionPerformed
        for (Fonction f : arr_fct) {
            if (modelcmb_fct.getSelectedItem().equals(f)) {
                fct = f;
                break;
            }
        }
        fctn = new Fonctionnaire(jTextField1.getText(),
                jTextField2.getText(), jTextField3.getText(), jTextField4.getText(),
                 jTextField5.getText(), fct);
        gst_fonctionnaire.InsertData(fctn);
        ShowData();

    }//GEN-LAST:event_btn_ajtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FonctionnaireForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FonctionnaireForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FonctionnaireForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FonctionnaireForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FonctionnaireForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajt;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_sup;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
