/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ma.project.forms;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import ma.bean.project.Fonction;
import ma.bean.project.MyStyles;
import ma.project.service.GestionFonction;

/**
 *
 * @author Hakim
 */
public class FonctionForm extends javax.swing.JFrame {

    /**
     * Creates new form FonctionForm
     */
    DefaultTableModel tablemodel;
    Fonction fct;
    ArrayList<Fonction> arr_fct;
    GestionFonction gst_fonction = new GestionFonction();

    public FonctionForm() {
        initComponents();
        tablemodel = (DefaultTableModel) jTable1.getModel();
        ShowData();
        btn_mod.setEnabled(false);
        btn_sup.setEnabled(false);

        MyStyles.GetMyStyle(btn_ajt, btn_mod, btn_sup, lbl_bg, this);

    }

    public void ShowData() {

        arr_fct = gst_fonction.ShowData();

        int rowCount = tablemodel.getRowCount();

        for (int i = 0; i < rowCount; i++) {
            tablemodel.removeRow(i);
        }

        for (Fonction o : arr_fct) {

            tablemodel.addRow(new Object[]{o.getIdFonction(), o.getFonction()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_ajt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btn_mod = new javax.swing.JButton();
        btn_sup = new javax.swing.JButton();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(138, 224, 123, 20);

        jLabel1.setText("Fonction");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(69, 227, 41, 14);

        btn_ajt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajtActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ajt);
        btn_ajt.setBounds(175, 262, 33, 9);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fonction"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 57, 337, 144);

        jLabel2.setText("Gestion des Fonctions");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(118, 32, 105, 14);

        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mod);
        btn_mod.setBounds(226, 262, 33, 9);

        btn_sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sup);
        btn_sup.setBounds(277, 262, 33, 9);
        getContentPane().add(lbl_bg);
        lbl_bg.setBounds(0, 0, 360, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        arr_fct = gst_fonction.ShowData();
        for (Fonction o : arr_fct) {
            if (tablemodel.getValueAt(jTable1.getSelectedRow(), 0).equals(o.getIdFonction())) {
                jTextField1.setText(o.getFonction());
                break;
            }
        }

        btn_mod.setEnabled(false);
        btn_sup.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_ajtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajtActionPerformed
        fct = new Fonction(jTextField1.getText());
        gst_fonction.InsertData(fct);
        ShowData();
    }//GEN-LAST:event_btn_ajtActionPerformed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        fct = new Fonction((int) tablemodel.getValueAt(jTable1.getSelectedRow(), 0), jTextField1.getText());
        gst_fonction.UpdateData(fct);
        ShowData();
    }//GEN-LAST:event_btn_modActionPerformed

    private void btn_supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supActionPerformed
        fct = new Fonction((int) tablemodel.getValueAt(jTable1.getSelectedRow(), 0));
        gst_fonction.DeleteData(fct);
        ShowData();
    }//GEN-LAST:event_btn_supActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FonctionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FonctionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FonctionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FonctionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FonctionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajt;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_sup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_bg;
    // End of variables declaration//GEN-END:variables
}
