/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ma.project.forms;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import ma.bean.project.Auteur;
import ma.bean.project.MyStyles;
import ma.project.service.GestionAuteur;

/**
 *
 * @author Hakim
 */
public class GestionAuteurForm extends javax.swing.JFrame {

    /**
     * Creates new form GestionAuteur
     */
    GestionAuteur gst_aut = new GestionAuteur();

    public DefaultTableModel tablemodel;

    ArrayList<Auteur> aut;
    Auteur at;

    BufferedImage image = null;
    File f = null;
    int width = 250;
    int height = 250;
    boolean choosed = false;
    File selectedFile;
    String path;
    int result;
    FileNameExtensionFilter filter;
    JFileChooser file;

    public GestionAuteurForm() {
        initComponents();

        jLabel5.setIcon(new ImageIcon(new ImageIcon("src\\files\\close.png").getImage()
                .getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_SMOOTH)));

        jLabel3.setIcon(new ImageIcon(new ImageIcon("src\\files\\upload.png").getImage()
                .getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH)));
        jLabel4.setIcon(new ImageIcon(new ImageIcon("src\\files\\png\\users.png").getImage()
                .getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH)));
        tablemodel = (DefaultTableModel) jTable1.getModel();
        addAuteur();

        MyStyles.GetMyStyle(btn_ajt, btn_mod, btn_sup, lbl_bg, this);

    }

    private void addAuteur() {

        aut = gst_aut.ShowData();
        int rowCount = tablemodel.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            tablemodel.removeRow(0);
        }

        for (Auteur au : aut) {
            JLabel lbl = new JLabel();
            if (!au.getPhoto().equalsIgnoreCase("")) {
                lbl.setIcon(new ImageIcon(new ImageIcon(au.getPhoto())
                        .getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH)));
            } else {
                lbl.setText("No Image View");
            }

            tablemodel.addRow(new Object[]{au.getIdAut(), au.getNom(), au.getDateN(), lbl});
        }
        jTable1.setRowHeight(40);

        jTable1.getColumn("Photo").setCellRenderer(new Labelrenderer());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btn_sup = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();
        btn_ajt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nom");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(48, 111, 21, 14);

        jLabel2.setText("Date Naissance");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(48, 154, 74, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ma/project/forms/upload.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 97, 96, 71);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(167, 108, 123, 20);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(167, 148, 123, 20);

        btn_sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_supMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_supMouseExited(evt);
            }
        });
        btn_sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sup);
        btn_sup.setBounds(289, 373, 50, 50);

        btn_mod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_modMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_modMouseExited(evt);
            }
        });
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mod);
        btn_mod.setBounds(221, 373, 50, 50);

        btn_ajt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ajt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ajtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ajtMouseExited(evt);
            }
        });
        btn_ajt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajtActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ajt);
        btn_ajt.setBounds(153, 373, 50, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom", "Date Naissance", "Photo"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 199, 487, 156);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(167, 29, 123, 50);

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(479, 0, 28, 32);

        lbl_bg.setText("jLabel6");
        getContentPane().add(lbl_bg);
        lbl_bg.setBounds(0, 0, 510, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String testchooser(String path, boolean choosed) {
        if (choosed) {
            //read image
            try {
                f = new File(path); //image file path
                image = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
                image = ImageIO.read(f);
                System.out.println("Reading complete.");
            } catch (IOException e) {
                System.out.println("Error: " + e);
            }
            //write image
            try {
                LocalDateTime now = LocalDateTime.now();
                path = "src\\files\\png\\" + jTextField1.getText() + now.getDayOfMonth() + now.getMonthValue() + now.getYear() + ".jpg";
                f = new File(path);  //output file path
                ImageIO.write(image, "jpg", f);

                System.out.println("Writing complete.");
            } catch (IOException e) {
                System.out.println("Error: " + e);
            }
            return path;
        } else {
            path = "";
            return path;
        }

    }

    private void btn_ajtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajtActionPerformed
        path = testchooser(path, choosed);
        at = new Auteur(jTextField1.getText(), jDateChooser1.getDate(), path);
        gst_aut.InsertData(at);
        addAuteur();
    }//GEN-LAST:event_btn_ajtActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter the files
        filter = new FileNameExtensionFilter("*.Images", "jpg", "png");
        file.addChoosableFileFilter(filter);
        result = file.showSaveDialog(null);
        //if the user click on save in Jfilechooser
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = file.getSelectedFile();
            path = selectedFile.getAbsolutePath();
//               JOptionPane.showMessageDialog(this,path);
            jLabel3.setIcon(new ImageIcon(new ImageIcon(path).getImage()
                    .getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH)));
            choosed = true;

        }
//else if (result == JFileChooser.CANCEL_OPTION) {
//            JOptionPane.showMessageDialog(this, "No Image Selected");
//            path = "";
//
//        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        for (Auteur auteur : aut) {
            if (tablemodel.getValueAt(jTable1.getSelectedRow(), 0).equals(auteur.getIdAut())) {
                jTextField1.setText(auteur.getNom());
                jDateChooser1.setDate(auteur.getDateN());
                jLabel3.setIcon(new ImageIcon(new ImageIcon(auteur.getPhoto()).getImage()
                        .getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH)));
                break;
            }
        }
        btn_mod.setEnabled(true);
        btn_sup.setEnabled(true);

    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        at = new Auteur((int) tablemodel.getValueAt(jTable1.getSelectedRow(), 0), jTextField1.getText(), jDateChooser1.getDate(), path);
        gst_aut.UpdateData(at);
        addAuteur();
    }//GEN-LAST:event_btn_modActionPerformed

    private void btn_supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supActionPerformed
        at = new Auteur((int) tablemodel.getValueAt(jTable1.getSelectedRow(), 0), jTextField1.getText(), jDateChooser1.getDate(), path);
        gst_aut.DeleteData(at);
        addAuteur();

    }//GEN-LAST:event_btn_supActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        menuauthor m = new menuauthor();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btn_ajtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ajtMouseEntered
        btn_ajt.setIcon(new ImageIcon(new ImageIcon("src\\files\\add_clicked.png").getImage()
                .getScaledInstance(50, 50, Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_btn_ajtMouseEntered

    private void btn_ajtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ajtMouseExited
        btn_ajt.setIcon(new ImageIcon(new ImageIcon("src\\files\\add.png").getImage()
                .getScaledInstance(50, 50, Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_btn_ajtMouseExited

    private void btn_modMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modMouseEntered
        btn_mod.setIcon(new ImageIcon(new ImageIcon("src\\files\\edit_clicked.png").getImage()
                .getScaledInstance(50, 50, Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_btn_modMouseEntered

    private void btn_modMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modMouseExited
        btn_mod.setIcon(new ImageIcon(new ImageIcon("src\\files\\edit.png").getImage()
                .getScaledInstance(50, 50, Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_btn_modMouseExited

    private void btn_supMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supMouseEntered
        btn_sup.setIcon(new ImageIcon(new ImageIcon("src\\files\\delete_clicked.png").getImage()
                .getScaledInstance(50, 50, Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_btn_supMouseEntered

    private void btn_supMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supMouseExited
        btn_sup.setIcon(new ImageIcon(new ImageIcon("src\\files\\delete.png").getImage()
                .getScaledInstance(50, 50, Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_btn_supMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAuteurForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAuteurForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAuteurForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAuteurForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionAuteurForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajt;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_sup;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_bg;
    // End of variables declaration//GEN-END:variables
}
