/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ma.project.forms;

import java.awt.AlphaComposite;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Menu;
import java.awt.MenuBar;
import java.awt.MenuItem;
import java.awt.SplashScreen;
import javax.swing.ImageIcon;

/**
 *
 * @author Hakim
 */
public class Launcher extends javax.swing.JFrame {

    /**
     * Creates new form Launcher
     */
    boolean exist = false;

    public Launcher() {
        initComponents();

        lbl_livre.setIcon(new ImageIcon(new ImageIcon("src\\files\\icons\\livre2.png").getImage()
                .getScaledInstance(90, 90, Image.SCALE_SMOOTH)));

        lbl_auteur.setIcon(new ImageIcon(new ImageIcon("src\\files\\icons\\auteur.png").getImage()
                .getScaledInstance(90, 90, Image.SCALE_SMOOTH)));

        lbl_fonction.setIcon(new ImageIcon(new ImageIcon("src\\files\\icons\\fonction.png").getImage()
                .getScaledInstance(90, 90, Image.SCALE_SMOOTH)));

        lbl_empriente.setIcon(new ImageIcon(new ImageIcon("src\\files\\icons\\emprinte.png").getImage()
                .getScaledInstance(90, 90, Image.SCALE_SMOOTH)));

        lbl_fonctionnaire.setIcon(new ImageIcon(new ImageIcon("src\\files\\icons\\fonctionnaire.png").getImage()
                .getScaledInstance(90, 90, Image.SCALE_SMOOTH)));

        lbl_adherant.setIcon(new ImageIcon(new ImageIcon("src\\files\\icons\\adherant.png").getImage()
                .getScaledInstance(90, 90, Image.SCALE_SMOOTH)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_livre = new javax.swing.JLabel();
        lbl_auteur = new javax.swing.JLabel();
        lbl_fonction = new javax.swing.JLabel();
        lbl_empriente = new javax.swing.JLabel();
        lbl_fonctionnaire = new javax.swing.JLabel();
        lbl_adherant = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 102, 0));

        jLabel1.setText("Gestion De Bibiotique");

        lbl_livre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/livre2.png"))); // NOI18N
        lbl_livre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_livre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_livreMouseClicked(evt);
            }
        });

        lbl_auteur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/auteur.png"))); // NOI18N
        lbl_auteur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_auteur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_auteurMouseClicked(evt);
            }
        });

        lbl_fonction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/fonction.png"))); // NOI18N
        lbl_fonction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_fonction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_fonctionMouseClicked(evt);
            }
        });

        lbl_empriente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/emprinte.png"))); // NOI18N
        lbl_empriente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_empriente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_emprienteMouseClicked(evt);
            }
        });

        lbl_fonctionnaire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/fonctionnaire.png"))); // NOI18N
        lbl_fonctionnaire.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_fonctionnaire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_fonctionnaireMouseClicked(evt);
            }
        });

        lbl_adherant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/adherant.png"))); // NOI18N
        lbl_adherant.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_adherant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_adherantMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_livre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_fonctionnaire, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_auteur, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_adherant, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_fonction, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_empriente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(108, 108, 108)))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_adherant, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(lbl_empriente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_fonctionnaire, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_auteur, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_livre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_fonction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_auteurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_auteurMouseClicked

//        if (!exist) {
        menuauthor m = new menuauthor();
        m.setVisible(true);
//            exist = true;
//        }

    }//GEN-LAST:event_lbl_auteurMouseClicked

    private void lbl_livreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_livreMouseClicked
        menubook m = new menubook();
        m.setVisible(true);

    }//GEN-LAST:event_lbl_livreMouseClicked

    private void lbl_fonctionnaireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_fonctionnaireMouseClicked
        FonctionnaireForm o = new FonctionnaireForm();
        o.setVisible(true);
    }//GEN-LAST:event_lbl_fonctionnaireMouseClicked

    private void lbl_adherantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_adherantMouseClicked
        AdherantForm o = new AdherantForm();
        o.setVisible(true);
    }//GEN-LAST:event_lbl_adherantMouseClicked

    private void lbl_fonctionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_fonctionMouseClicked
        FonctionForm o = new FonctionForm();
        o.setVisible(true);
    }//GEN-LAST:event_lbl_fonctionMouseClicked

    private void lbl_emprienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_emprienteMouseClicked
        EmprinteForm o = new EmprinteForm();
        o.setVisible(true);
    }//GEN-LAST:event_lbl_emprienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Thread.sleep(3000);
                    new Launcher().setVisible(true);

                } catch (Exception e) {
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_adherant;
    private javax.swing.JLabel lbl_auteur;
    private javax.swing.JLabel lbl_empriente;
    private javax.swing.JLabel lbl_fonction;
    private javax.swing.JLabel lbl_fonctionnaire;
    private javax.swing.JLabel lbl_livre;
    // End of variables declaration//GEN-END:variables
}
